### ISSUE TITLE
whisper-AI-exec-script missing endpoint (?)

### ISSUE THREAD

**Issue by stefanosgeo** [opencast/helper-scripts#64]
I tried the Whisper ASR, installed in the host and not as a docker container.

API endpoint (get-vtt) is missing

https://github.com/opencast/helper-scripts/blob/a46f18a0cd87dc0464222fbd199b4bd0dca6d784/whisper-AI-exec-script/whisper-getvtt.sh#L20

Curl returns {"detail":"Not Found"} and saved bei WOH as subtitle-output.vtt

If I replace the endpoint with asr I get back the text and segements as json data saved in the subtitle-output.vtt

**Comment by gregorydlogan** [comment]
Over to @mliradelc since he worked on that recently.

**Comment by mliradelc** [comment]
Hi, since last week I was sick. I will look it tomorrow/today depending on the timezone.

**Comment by mliradelc** [comment]
Now, I see the problem, [Whisper ASR Webservice](https://github.com/ahmetoner/whisper-asr-webservice) has been updated and changed the URL. You can use an earlier version of the service.

@stefanosgeo feel free to submit a PR to reflect the latest changes. 

By the way, Opencast 13 includes native integration with Whisper, but if you are using OC 12 or 11, it is possible to backport it because is the same implementation as Vosk

**Comment by stefanosgeo** [comment]
I would really like to submit a PR but I am not a Java programmer :smile:  and I don't know how to handle the response with the new json data and create a .vtt based on the segments key, value pairs .

 I am doing it in my PHP API, but I don't have any idea how I can do it in Java.

I have Opencast 13 installed on our servers and it is working out of the box with whisper! Many thanks for this. My main concern is who much workload can our workers handle. They are CPU and not GPU nodes, that's I would like this approach, having Whisper in a separate non-worker GPU Server.

**Comment by mliradelc** [comment]
I read the modifications, you should use the container version [v1.0.2-beta](https://github.com/ahmetoner/whisper-asr-webservice/releases/tag/v1.0.2-beta) later versions have changed the endpoint.

I will look if I can change the endpoint, making curl to `.../asr=vtt` should be enough to create a VTT file instead a JSON file.

From your question regarding OC 13. You can set a work limit in the ASR settings of opencast, with that, you will avoid overloading a machine with more than one/two translation works or put on the CPU machines a 0 threshold, so they will never be use for Transcription jobs

**Comment by stefanosgeo** [comment]
that's a good idea. Let me try the script with

POST "$whisperServer/asr?task=transcribe&output=vtt

and I will report back. If it is working I will make a PR.

**Comment by stefanosgeo** [comment]
I tested an it's working and also did a PR. Feel free to test my PR again with your Docker image

**Comment by mliradelc** [comment]
Niice, tomorrow I will test it :D
